import "./global.css";

import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";

import ReactQueryProvider from "./components/providers/ReactQueryProvider";
import AuthSessionProvider from "./components/providers/AuthSessionProvider";

const sourceSans3 = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sourceSans3.className}>
        <AuthSessionProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
