version: "3"

services:
  database:
    image: postgres:16
    restart: always
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  cache:
    image: redis:7.2
    ports:
      - 6379:6379
    restart: always
